MotorsNode:
    ros__parameters:
        can0_startID: 1
        can0_endID: 6
        can1_startID: 7
        can1_endID: 12
        kp: [125.0, 150.0, 125.0, 150.0, 100.0, 100.0]
        kd: [4.0, 4.5, 4.0, 4.5, 3.0, 3.0]


