Motors:
    ros__parameters:
        can0_startID: 1
        can0_endID: 6
        can1_startID: 7
        can1_endID: 12
        kp: [150.0, 120.0, 150.0, 75.0, 75.0, 75.0]
        kd: [4.0, 4.0, 2.0, 3.0, 2.0, 2.0]


